#!/bin/bash
set -euo pipefail

# Setup script for 1-bit Bonsai experiments.
# Clones repos, downloads models, verifies toolchain.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
WORK_DIR="${PROJECT_DIR}/work"

echo "=== 1-bit Bonsai Experiment Setup ==="
echo "Project dir: ${PROJECT_DIR}"
echo "Work dir: ${WORK_DIR}"

mkdir -p "${WORK_DIR}"
mkdir -p "${SCRIPT_DIR}/data"
mkdir -p "${SCRIPT_DIR}/results"

# --- Clone Bonsai-demo ---
BONSAI_DIR="${WORK_DIR}/Bonsai-demo"
if [ ! -d "${BONSAI_DIR}" ]; then
    echo "Cloning Bonsai-demo..."
    git clone https://github.com/MaanasSathaye/Bonsai-demo.git "${BONSAI_DIR}"
else
    echo "Bonsai-demo already cloned."
fi

# --- Clone ANE repo ---
ANE_DIR="${WORK_DIR}/ANE"
if [ ! -d "${ANE_DIR}" ]; then
    echo "Cloning ANE training repo..."
    git clone https://github.com/MaanasSathaye/ANE.git "${ANE_DIR}"
else
    echo "ANE repo already cloned."
fi

# --- Run Bonsai-demo setup (downloads models + builds llama.cpp) ---
echo ""
echo "=== Setting up Bonsai-demo ==="
echo "This downloads ~1.15 GB of model weights and builds llama.cpp."
echo "Set BONSAI_MODEL=8B (default) to control which model size."
echo ""

cd "${BONSAI_DIR}"
export BONSAI_MODEL="${BONSAI_MODEL:-8B}"

if [ ! -f "${BONSAI_DIR}/bin/llama-bench" ] && [ ! -f "${BONSAI_DIR}/build/bin/llama-bench" ]; then
    echo "Running Bonsai-demo setup.sh..."
    ./setup.sh
else
    echo "Bonsai-demo already set up (llama-bench binary found)."
fi

# --- Locate binaries ---
LLAMA_BENCH=""
LLAMA_PPL=""
for dir in "${BONSAI_DIR}/bin" "${BONSAI_DIR}/bin/mac" "${BONSAI_DIR}/bin/linux" "${BONSAI_DIR}/build/bin"; do
    if [ -x "${dir}/llama-bench" ]; then
        LLAMA_BENCH="${dir}/llama-bench"
    fi
    if [ -x "${dir}/llama-perplexity" ]; then
        LLAMA_PPL="${dir}/llama-perplexity"
    fi
done

echo ""
echo "=== Binary locations ==="
echo "llama-bench: ${LLAMA_BENCH:-NOT FOUND}"
echo "llama-perplexity: ${LLAMA_PPL:-NOT FOUND}"

# --- Locate Bonsai model ---
BONSAI_GGUF=""
for f in "${BONSAI_DIR}"/models/gguf/${BONSAI_MODEL}/*.gguf; do
    if [ -f "$f" ]; then
        BONSAI_GGUF="$f"
        break
    fi
done
echo "Bonsai GGUF: ${BONSAI_GGUF:-NOT FOUND}"

# --- Download WikiText-2 ---
WIKITEXT="${SCRIPT_DIR}/data/wikitext2.txt"
if [ ! -f "${WIKITEXT}" ]; then
    echo ""
    echo "Downloading WikiText-2 test set..."
    curl -L -o "${WIKITEXT}" \
        "https://huggingface.co/datasets/gg-hf/wikitext-2-raw-v1/resolve/main/wikitext-2-raw/wiki.test.raw" \
        2>/dev/null || echo "WARNING: WikiText-2 download failed. Perplexity experiments will not work."
else
    echo "WikiText-2 already downloaded."
fi

# --- Write config file for other scripts ---
CONFIG="${SCRIPT_DIR}/config.env"
cat > "${CONFIG}" <<EOF
# Auto-generated by setup.sh on $(date -Iseconds)
WORK_DIR="${WORK_DIR}"
BONSAI_DIR="${BONSAI_DIR}"
ANE_DIR="${ANE_DIR}"
LLAMA_BENCH="${LLAMA_BENCH}"
LLAMA_PPL="${LLAMA_PPL}"
BONSAI_GGUF="${BONSAI_GGUF}"
BONSAI_MODEL="${BONSAI_MODEL}"
WIKITEXT="${WIKITEXT}"
RESULTS_DIR="${SCRIPT_DIR}/results"
EOF

echo ""
echo "=== Setup complete ==="
echo "Config written to: ${CONFIG}"
echo ""
echo "Next steps:"
echo "  1. ./run_throughput.sh    # Experiment 1: burst throughput"
echo "  2. ./run_sustained.sh    # Experiment 2: sustained throughput"
echo "  3. ./run_perplexity.sh   # Experiment 3: perplexity"
